### ISSUE TITLE
Grey Loading Overlay Doesn't Close After Loading Map

### ISSUE THREAD

**Issue by Gideon2361** [Toliann/Spectralis#1]
First off, this is my absolute favorite map.

The issue...when loading into this map, the dark overlay the game uses to display the random seed it used doesn't go away after the map loads.  The seed text goes away, but the dark overlay doesn't, which means the brightness has to be maxed to play the map.

This happens for both me and one of my friends, but not for my roomie.

If there's anything I can do to help debug this, I'm happy to stream for you.

**Comment by Gideon2361** [comment]
Screenshot of what happens to me.

![Screenshot 2024-04-11 194644](https://github.com/Toliann/Spectralis/assets/26071698/871c4a15-345a-4395-bf2b-173a93bc3521)

**Comment by Toliann** [comment]
It's probably because of post-processing, I've turned up the moon's brightness a bit

**Comment by Toliann** [comment]
Fixed in the new version
